# Generated by Django 4.1.5 on 2023-12-15 08:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('grid_size', models.IntegerField(default=3)),
                ('alignment', models.IntegerField(default=3)),
                ('created_at', models.DateField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('visibility', models.CharField(default='PUBLIC', max_length=20)),
                ('created_at', models.DateField(blank=True, default=datetime.datetime.now)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Morpion.gameconfig')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Morpion.user')),
            ],
        ),
    ]
