# Generated by Django 4.2.8 on 2023-12-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Morpion', '0002_game_access_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='board',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='game',
            name='current_player',
            field=models.IntegerField(default=1),
        ),
    ]
