# Generated by Django 4.2.8 on 2024-01-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Morpion', '0005_alter_game_current_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='symbol',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
