# Generated by Django 4.2.8 on 2024-01-07 11:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Morpion', '0006_game_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(default='NOT_STARTED', max_length=20),
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.PositiveIntegerField()),
                ('created_at', models.DateField(blank=True, default=datetime.datetime.now)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Morpion.gameconfig')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Morpion.user')),
            ],
        ),
    ]
